# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08529f7ffb23120b53fe7c8da9460afaa53540a6b138165a2ad3f52d9b708cb8292aef834f1e3e3ba5f94971ef8fbbf4da10fa077db5e500324427dbdadd6ecd

test:
  secret_key_base: d876f72359702875359662ce76eb81dae000e541483e392c7ae752a788f3d9f40a3e1c67756a29e25bdfe87515f74fd4cbc5a461d650884e3e81995eb90075fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
