# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ac5212b4e934dbcefbf8ceb35929a81d34eb090a3dc417163b23dbb22cad99da1d794d0edca260fb287878e13621994e4fc6bd79ff99dcd6d031d962e8428a

test:
  secret_key_base: c482a32ef1afbbfb14d2e2a20c7256ba0d92619ba7211043a78182553bec25ba2b4fa5aa3bfa30fef50ad583fc5f6ce5a2c7dfe6376e4fe3771c77fd6131806b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
