# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d783a40eb173ec16ae73e08b2596864363c6eb073b83a1ea6b923e1c508f704d69585f6e9756744a426fdcff394a12f9c2344dee90fb7c56e3e5e320bc903f6

test:
  secret_key_base: d5c6474fe9a2b3eb0d8f7d749a30aa72244db896a5ff3d74c9e01282cc66f678f0d24141eaf7ef9b0dacc45ec2a55dabff86294473d59e39e64420c6b7e28f8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
