# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c3de8cb8b87930d7071a1b075f15fa84390b4ac223c2d5781cf8a1ea5ab5222eea921e636076c4a84ea42a9f531c8a344be88ec4f4f29aa2df847aa75166a4

test:
  secret_key_base: 28853b6dc1f643e0a4e6be090c2ad57ece4c04b3c15c3d08faa87e9dee3650e5bdece2992adfef3101dda4f310701c3cf33dea01bf954c62b74078299ae19402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
