# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f34b61931e05b9cfff2e30b2d7a339c23fe04cc9b9b8cf5d9f9d3dd537ce1e1a316499c20f99a4d868f6a94e1a1ec69313f5ef3d13e8a256acd080f2784c3f8

test:
  secret_key_base: 00137329a399305f5e1d413341e8653f10d3abb7073036da75ecf35cf577f61e54a1afa055f7437ee84bdb31174de766ec04d6cd3b6b6c353229fdee8ecdab9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
