# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79abf0b975e8464086661b9e5e0f2ac4f76dfc9d69fd79ec3945409efe9f0e257630f08f00b41e2136d082b7294cd62754ffaa8f76c2065a373a236996f674ee

test:
  secret_key_base: 4aec1ef59058911c66b5e8b06c70ffd014e2a959bb8ce6812aed67cfca8f07a152fe78a0719822e86ef19522db930088c3d7b5578ba16ab9df8fdf005cbed7ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
